### ISSUE TITLE
iotduino dependency

### ISSUE THREAD

**Issue by biggestsonicfan** [rwaldron/pcduino-io#2]
Greetings,

I am trying to get a basic "blink" node working, however, it looks like pcDuino-IO relies on [IoTDuino](https://github.com/dimircea/iotduino) to function... but IoTDuino never supported the I2C Bus, which makes me wonder how pcDuino-IO ever worked... ever...

Here is a snippit of the thrown error:
```
internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module 'iotduino'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/linaro/Downloads/johnny-test/node_modules/pcduino-io/lib/pcduino-io.js:15:3)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
```

The owner of the repo has also confirmed [there will be no more development done on the IoTDuino node module.](https://github.com/dimircea/iotduino/issues/2#issuecomment-449312444)..

Please advise...

**Comment by biggestsonicfan** [comment]
Any updates to this issue?

**Comment by rwaldron** [comment]
> which makes me wonder how pcDuino-IO ever worked... ever...

Because it uses `i2c-bus` for I2C support. Both `iotduino` and `i2c-bus` are optional dependencies (I don't remember why I made them optional).

**Comment by biggestsonicfan** [comment]
Ahhh, interesting! I will have to retry this once I get my pcduino up and running again! Thanks!
